### PR TITLE
JSP v2.3.0 compatibility fixes

### PR DESCRIPTION
**Pull request by ghost**
I think this covers it all with the exception of Library Tree in Folder view mode. I honestly don't know how to fix that. Pinging @Wil-B - IIRC someone on hydrogenaud.io has requested a fixed version so he might have some progress on this.

**edited**; made it backwards compatible as well

### CODE REVIEW

**Comment by Wil-B** [comment]
There will be a maintenance update to the JScript panel version of library tree shortly: 1.4.0.4. There are no new features compared with 1.4.0.3. Main changes are:

CHG: Themes: switched to GetColourSchemeJSON, due to removal of GetColourScheme (but I think you removed that for Georgia)
CHG: View by folder structure now uses faster GetLibraryRelativePaths(). This is by far and away the biggest change. It effects both library initialisation and the library update methods. I actually added it a long time ago, but it was never in a release version. There are also some bug fixes in there and reworking of the library update code that effect all views. Likely you can just copy & paste the new functions, which can easily be identified by doing a document compare vs 1.4.0.3 in Word etc.
CHG: Removed the 500,000 limit in sending tracks to playlist.

There may be some other minor JSP compatibility changes, which you should easily see by document compare.

As AndreaT, who has a huge 600K library on I believe an aging pc, has come across some memory issues with the SMP version I was probably going to wait before properly releasing the JSP version to see if anything relevant emerges...

But if you want what I have now let me know.

HTH

**Comment by kbuffington** [comment]
This is awesome @marc2k3 . I had made these changes myself and spent about half a second thinking about backwards compatibility before not bothering. You're smart and this is better.

@Wil-B Sounds good. I made significant cleanup/refactor on the library tree for my own personal needs so I can't just integrate an updated version. When you've got a solution I will check out a diff and see what I can port in.

**Comment by ghost** [comment]
Regarding backwards compatibility, I only tested v2.2.2.4. I can't guarantee it will work on earlier versions. Anyone on the 2.2.x branch hesitant on upgrading to 2.3 should have no problems upgrading to 2.2.2.4 which is available on my old versions page.

https://github.com/marc2k3/foo_jscript_panel/wiki/Old-Versions

**Comment by ghost** [comment]
I see you've included JSP on your download page. I hope you can remove it ASAP as it has a rather nasty bug with the editor dialog. A fixed version has just been uploaded...

https://github.com/marc2k3/foo_jscript_panel/releases

**Comment by kbuffington** [comment]
Yeah, I saw that got updated this morning and updated the version.

**Pull request merged**
